### ISSUE TITLE
Idempotency issue for hashivault_db_secret_engine_config

### ISSUE THREAD

**Issue by Roxyrob** [TerryHowe/ansible-modules-hashivault#381]
`hashivault_db_secret_engine_config` module always apply (change) breaking idempotency.

to reproduce run multiple times this simple code:
<br>
<pre>
- hashivault_secret_engine:
    backend: database
    name: testpath
    state: present

- hashivault_db_secret_engine_config:
    mount_point: testpath
    name: testdbname
    plugin_name: 'mysql-database-plugin'
    state: present
    connection_details:
      username: "{{ vault_user }}"
      password: "{{ vault_pwd }}"
      connection_url: "dummyconnection"
    verify_connection: false
</pre>

on every run it returns:

<pre>
TASK [myrole-name : hashivault_db_secret_engine_config] *******************************************************************************************************************************
<b>[WARNING]: Module did not set no_log for password_policy</b>  <b><-- see ansible versioni below</b>
<b>changed</b>: [localhost] <b><-- it change on every run</b>
</pre>

This is a serious issue as we **cannot rotate vault root database credential** as `hashivault_db_secret_engine_config` re-apply on every run (reconfiguring also the original password) also if nothing is changed. 

**ansible --version**
<pre>
ansible [core 2.12.1]
packages/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.3
</pre>

**Comment by emper0r** [comment]
hi @TerryHowe  we are getting same issue as explained @Roxyrob . is very useful if this would be take in consideration soon.

**Comment by TerryHowe** [comment]
Must be a change for something underlying here that I assume this is related to the other issue you created.

**Comment by TerryHowe** [comment]
Idempotent check https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_db_secret_engine_config.py#L141

**Comment by Roxyrob** [comment]
> Idempotent check https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_db_secret_engine_config.py#L141

I don't know python so well, but for the code you pointed me, `desired_state` and `current_state` cannot be different as nothing change between run, but the last elif seems to set `changed = True` anyway if `state == present`, I'm wrong ?

note also warning `[WARNING]: Module did not set no_log for password_policy`


> Must be a change for something underlying here that I assume this is related to the other issue you created.

Not relate to other issue

**Comment by TerryHowe** [comment]
I think this should resolve this issue https://github.com/TerryHowe/ansible-modules-hashivault/pull/385/files

Although no_log should probably be set as well

**Comment by TerryHowe** [comment]
The last elif was checking if it is any other key, the values should match.

**Comment by TerryHowe** [comment]
I don't think it makes sense to no_log on password_policy since it is a policy, but maybe do it anyway to avoid the warning

**Comment by ayav09** [comment]
I'm creating another PR to fix some of the other idempotency issues. Mount point isn't specified when retrieving the current state from vault so it thinks it doesn't presently "exist". Password policy is also returned as an empty string from vault so that is always not matching None. We can probably just set the default to an empty string in the argspec as a quick fix.

I agree no_log isn't necessary on password_policy but we can just explicitly set it to False to prevent the warnings.

**Comment by Roxyrob** [comment]
Release 4.6.6 worked for no_log warning, but **idempotency issues are still present**, with changed status on every run

**Comment by Roxyrob** [comment]
It seems that also state for this module has a minor issue as `state: absent` does not remove config from vault.

If I could ever go deep on python and ansible module development standards I will be happy to get involved in the fix of hashivault modules issues.

**Comment by Roxyrob** [comment]
For the **no_log warning** issues in general probably the `ansible heuristically checks behavior` outlined here can help: [Confusing warning form postgresql_user module: "Module did not set no_log for no_password_changes](https://github.com/ansible/ansible/issues/68106#issuecomment-596631184)

**Comment by Roxyrob** [comment]
Idempotency and state know works fine !
Thanks
